[versions]
androidDocumentationPlugin = "2.0.0"
ftc = "11.0.0"

[libraries]
android-documentation = { module = "org.jetbrains.dokka:android-documentation-plugin", version.ref = "androidDocumentationPlugin" }
ftc-robot-core = { group = "org.firstinspires.ftc", name = "RobotCore", version.ref = "ftc" }
ftc-hardware = { group = "org.firstinspires.ftc", name = "Hardware", version.ref = "ftc" }
annotations = { group = "org.jetbrains", name = "annotations", version = "23.0.0" }
dokka-java = "org.jetbrains.dokka:kotlin-as-java-plugin:2.0.0"

[bundles]
ftc = ["ftc-robot-core", "ftc-hardware"]
docs = ["dokka-java", "android-documentation"]

[plugins]
android-library = { id = "com.android.library", version = "8.7.3" }
deployer = { id = "io.deepmedia.tools.deployer", version = "0.18.0" }
dokka = { id = "org.jetbrains.dokka", version = "2.0.0" }